[profile.default]
solc_version = "0.8.18"
optimizer_runs = 10_000
fuzz = { runs = 512 }
remappings = [
  "ds-test/=lib/ds-test/src",
  "forge-std/=lib/forge-std/src",
  "solmate/=lib/solmate/",
  "openzeppelin/=lib/openzeppelin-contracts/",
  "openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
  "chainlink/=lib/chainlink-brownie-contracts/contracts/src/",
  "prb-math/=lib/prb-math/src"
]
auto_detect_remappings = false

[profile.ci]
verbosity = 3
fuzz = { runs = 10000 }

[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
bracket_spacing = false
int_types = "long"
multiline_func_header = "params_first"
